import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import * as sourceApi from "../src/index.js";
import { describe, expect, expectTypeOf, it } from "vitest";
import { z } from "zod";
import {
  BoundaryError,
  BundleDocumentLimits,
  BundleDocumentLimitsSchema,
  BundleInspectionInputSchema,
  BundleInspectionResultSchema,
  CanonicalSourceSchema,
  ComponentIdVersionRegistry,
  ComponentLogicalIdentitySchema,
  ComponentLocatorAuthorityRegistry,
  ComponentLocatorAuthoritySchema,
  ComponentLocatorClaimSchema,
  ComponentLocatorSourceRegistry,
  ComponentLocatorSourceSchema,
  ComponentLocatorTargetSchema,
  ContentDigestSchema,
  ContentManifestEntrySchema,
  ContentManifestSchema,
  createCompatibilityService,
  createContentIndex,
  createNodePluginInspector,
  createPluginInspectionService,
  reconcilePluginBundle,
  DEFAULT_MATERIALIZATION_LIMITS,
  ClaimConflictError,
  ClaimedSchema,
  CompatibilityEvaluationInputSchema,
  CompatibilityPolicyRegistry,
  CompatibilityPolicyRuleRegistry,
  CompatibilityPolicyRuleSchema,
  CompatibilityPolicyRulesSchema,
  CompatibilityReportSchema,
  ComponentAssessmentSchema,
  ComponentIdSchema,
  ComponentKindRegistry,
  ComponentSchema,
  ComponentVerdictRegistry,
  ComponentVerdictSchema,
  ConfigurationOptionSchema,
  ConfigurationValueKindRegistry,
  ConfigurationValueSchema,
  DiagnosticSchema,
  DomainContractError,
  ErrorCodeRegistry,
  ErrorCodeSchema,
  FatalBoundaryCodeSchema,
  ForeignComponentDeclarationSchema,
  ForeignComponentSchema,
  GitRevisionSchema,
  HookComponentSchema,
  HookEventSchema,
  HookHandlerSchema,
  HookHandlerVariantRegistry,
  JsonValueSchema,
  MCPFeatureSchema,
  MCPTransportSchema,
  MarketplaceAvailabilityRegistry,
  MarketplaceAvailabilitySchema,
  MarketplaceAuthoritySchema,
  MarketplaceDeclarationCategoryRegistry,
  MarketplaceEntryDeclarationSchema,
  MarketplaceInstallationPolicySchema,
  MarketplaceNameSchema,
  MarketplaceReadResultSchema,
  MarketplaceSourceSchema,
  MarketplaceSourceVariantRegistry,
  McpServerComponentSchema,
  NativeHostSchema,
  NormalizedMarketplaceEntrySchema,
  NormalizedMarketplaceSchema,
  NormalizedPluginSchema,
  NpmIntegritySchema,
  PluginComponentsSchema,
  PluginConfigurationSchema,
  PluginIdentitySchema,
  PluginKeySchema,
  PluginManifestClaimsSchema,
  PluginNameSchema,
  PluginSourceSchema,
  PluginSourceVariantRegistry,
  ProvenanceSchema,
  ReadResultSchema,
  ResolvedMarketplaceSourceSchema,
  ResolvedPluginSourceSchema,
  ResolvedPluginSourceVariantRegistry,
  RetainedMetadataSchema,
  RuntimeCapabilityAvailabilitySchema,
  RuntimeCapabilityIdSchema,
  RuntimeCapabilityRegistry,
  RuntimeCapabilityRegistrySchema,
  RuntimeCapabilitySnapshotSchema,
  RuntimeCapabilityStatusRegistry,
  RuntimeCapabilityStatusSchema,
  RuntimeRequirementAssessmentSchema,
  RuntimeRequirementIdSchema,
  RuntimeRequirementSchema,
  RuntimeRequirementStatusRegistry,
  RuntimeRequirementStatusSchema,
  SkillComponentSchema,
  SourceDocumentKindSchema,
  SourceHashSchema,
  SourceLocationSchema,
  createCompatibilityReport,
  deriveComponentId,
  createContentManifest,
  createNodeSourceMaterializers,
  createPluginIdentity,
  createSourceMaterializers,
  createResolvedMarketplaceSource,
  createResolvedPluginSource,
  deriveActivatable,
  diagnosticFromZodError,
  evaluateCompatibility,
  flattenComponents,
  verifyComponentId,
  formatPluginKey,
  hashCanonicalSource,
  hashContent,
  mergeEquivalentClaims,
  SourceMaterializationError,
  verifyContentManifest,
  verifyResolvedMarketplaceSource,
  verifyResolvedPluginSource,
  nonEmptyReadonly,
  parsePluginKey,
  schemaValues,
  serializeMarketplaceSource,
  serializePluginSource,
  claim,
  ActivationIntentSchema,
  CanonicalProjectRootSchema,
  GenerationSchema,
  HostConfigDocumentSchema,
  HostConfigDocumentSchemaV1,
  HostConfigSchemaFamily,
  ImmutableRevisionEvidenceSchema,
  InstalledPluginRecordSchema,
  InstalledRevisionRecordSchema,
  InstalledUserStateDocumentSchema,
  InstalledUserStateDocumentSchemaV1,
  InstalledUserStateSchema,
  InstalledUserStateSchemaFamily,
  MarketplaceConfigurationRecordSchema,
  MarketplaceContentRefSchema,
  MarketplaceSnapshotRecordSchema,
  PendingTransitionRefSchema,
  PluginConfigurationRefSchema,
  PluginContentRefSchema,
  PluginDataRefSchema,
  PointerDocumentKindSchema,
  PortableMarketplaceDeclarationSchema,
  PortableMarketplaceSourceSchema,
  PortablePluginConstraintSchema,
  PortablePluginDeclarationSchema,
  PortablePluginSourceSchema,
  PortableProjectDeclarationSchema,
  PortableProjectDeclarationSchemaV1,
  PortableProjectSchemaFamily,
  ProjectIdentitySchema,
  ProjectKeySchema,
  ProjectLocalStateDocumentSchema,
  ProjectLocalStateDocumentSchemaV1,
  ProjectLocalStateSchemaFamily,
  ProjectStateMutationInputSchema,
  ProjectStateMutationSchema,
  ReferenceIdentitySchema,
  ScopeContextSchema,
  ScopeReferenceSchema,
  StateBlobRefSchema,
  StateCodecError,
  StateCorruptionCodeSchema,
  StateCorruptionSchema,
  StateDocumentKindRegistry,
  StateDocumentKindSchema,
  StateDocumentPointerSchema,
  StateDocumentRegistry,
  StateLoadFailureSchema,
  StateMutationInputSchema,
  StateMutationSchema,
  StatePointersDocumentSchema,
  StatePointersDocumentSchemaV1,
  StatePointersSchemaFamily,
  StateReferenceKindRegistry,
  StateReferenceSchema,
  StateSchemaVersionSchema,
  TrustDecisionStatusSchema,
  TrustStateDocumentSchema,
  TrustStateDocumentSchemaV1,
  TrustStateRecordSchema,
  TrustStateSchemaFamily,
  TrustSubjectEvidenceSchema,
  TrustSubjectRefSchema,
  UpdateApplicationPreferenceSchema,
  UserStateMutationInputSchema,
  UserStateMutationSchema,
  assertPortableProjectDeclarationSafe,
  createInstalledPluginRecord,
  createInstalledRevisionRecord,
  createInstalledUserStateDocument,
  createMarketplaceSnapshotRecord,
  createProjectLocalStateDocument,
  createScopeContext,
  createStatePointersDocument,
  createTrustStateDocument,
  createTrustStateRecord,
  decodeInstalledPluginRecords,
  decodeInstalledUserPlugins,
  decodePortableProjectDeclaration,
  decodeProjectPlugins,
  decodeStateDocument,
  defineVersionedSchemaFamily,
  deriveMarketplaceContentRef,
  derivePendingTransitionRef,
  derivePluginConfigurationRef,
  derivePluginContentRef,
  derivePluginDataRef,
  deriveProjectKey,
  deriveStateBlobRef,
  deriveTrustSubject,
  deriveTrustSubjectRef,
  encodeStateDocument,
  getStateDocumentDefinition,
  hashStateDocument,
  isSafePortableRelativePath,
  migrateVersionedDocument,
  parsePortableProjectDeclaration,
  isVerifiedStateMutation,
  parseStateMutation,
  stateDocumentKinds,
  toScopeReference,
  validateStateMutation,
  verifyMarketplaceContentRef,
  verifyPendingTransitionRef,
  verifyPluginConfigurationRef,
  verifyPluginContentRef,
  verifyPluginDataRef,
  verifyStateBlobRef,
  verifyStatePointersScope,
  verifyTrustStateRecord,
  verifyTrustSubjectRef,
  type AgentSkillReader,
  type LifecycleStateStore,
  type Generation,
  type HostConfigDocumentV1,
  type InstalledUserStateDocumentV1,
  type ProjectLocalStateDocumentV1,
  type PortableProjectDeclarationV1,
  type StateDocumentByKind,
  type UserStateMutationInput,
  type ProjectStateMutationInput,
  type StateMutationInput,
  type UnverifiedStateMutation,
  type VerifiedStateMutation,
  type StateMutation,
  type StateCommitResult,
  type StateLoadResult,
  type StatePointersDocumentV1,
  type TrustStateDocumentV1,
  type UserGenerationSnapshot,
  type ProjectGenerationSnapshot,
  type BundleDocumentLimitsContract,
  type BundleInspectionInput,
  type BundleInspectionResult,
  type BundleReaderSet,
  type CompatibilityAssessmentRequest,
  type CompatibilityService,
  type PluginInspectionDependencies,
  type PluginInspectionService,
  type BundleReconciliationInput,
  type CompatibilityEvaluationInput,
  type CompatibilityPolicyDisposition,
  type CompatibilityPolicyRegistryType,
  type CompatibilityPolicyRule,
  type CompatibilityPolicySurface,
  type CompatibilityReport,
  type ComponentLocatorClaim,
  type ComponentLogicalIdentity,
  type ContentIndex,
  type ContentReadPort,
  type ContentDigest,
  type ContentManifest,
  type ContentManifestEntry,
  type Component,
  type ComponentAssessment,
  type ComponentId,
  type ComponentVerdict,
  type ConfigurationOption,
  type ConfigurationValue,
  type Diagnostic,
  type DomainContractError as DomainContractErrorType,
  type ErrorCode,
  type FatalBoundaryCode,
  type ForeignComponent,
  type ForeignComponentDeclaration,
  type GitRevision,
  type HookComponent,
  type HookHandler,
  type JsonValue,
  type MarketplaceAuthority,
  type MarketplaceAvailability,
  type MarketplaceEntryDeclaration,
  type MarketplaceInstallationPolicy,
  type MarketplaceName,
  type MarketplaceReadResult,
  type MarketplaceSource,
  type McpServerComponent,
  type NativeHost,
  type NormalizedMarketplace,
  type NormalizedMarketplaceEntry,
  type NormalizedPlugin,
  type NpmIntegrity,
  type PluginComponents,
  type PluginConfiguration,
  type PluginIdentity,
  type PluginKey,
  type PluginManifestClaims,
  type PluginName,
  type PluginSource,
  type Provenance,
  type ReadResult,
  type ResolvedMarketplaceSource,
  type ResolvedPluginSource,
  type RetainedMetadata,
  type RuntimeCapabilityAvailability,
  type RuntimeCapabilityId,
  type RuntimeCapabilityProbe,
  type RuntimeCapabilitySnapshot,
  type RuntimeRequirement,
  type RuntimeRequirementAssessment,
  type RuntimeRequirementId,
  type RuntimeRequirementStatus,
  type SkillComponent,
  type HookDocumentReader,
  type McpDocumentReader,
  type PluginManifestReader,
  type Sha256,
  type SourceContext,
  type SourceMaterializationDependencies,
  type StagingSlot,
  type SourceDocumentKind,
  type SourceHash,
  type SourceLocation,
  type Claimed,
  type CollectionReadResult,
} from "../src/index.js";

describe("explicit package API", () => {
  it("keeps the source barrel on the compiled package allowlist", () => {
    const compiledTest = readFileSync(resolve(process.cwd(), "test/compiled-package-import.mjs"), "utf8");
    const start = compiledTest.indexOf("const expectedExports = [");
    const end = compiledTest.indexOf("].sort();", start);
    expect(start).toBeGreaterThanOrEqual(0);
    expect(end).toBeGreaterThan(start);
    const expected = [...compiledTest.slice(start, end).matchAll(/"([^"]+)"/g)].map((match) => match[1]).sort();
    expect(Object.keys(sourceApi).sort()).toEqual(expected);
  });

  it("exposes the complete intended domain contract without adapters", () => {
    const symbols = [
      BoundaryError,
      BundleDocumentLimits,
      BundleDocumentLimitsSchema,
      BundleInspectionInputSchema,
      BundleInspectionResultSchema,
      CanonicalSourceSchema,
      ComponentIdVersionRegistry,
      ComponentLogicalIdentitySchema,
      ComponentLocatorAuthorityRegistry,
      ComponentLocatorAuthoritySchema,
      ComponentLocatorClaimSchema,
      ComponentLocatorSourceRegistry,
      ComponentLocatorSourceSchema,
      ComponentLocatorTargetSchema,
      ContentDigestSchema,
      ContentManifestEntrySchema,
      ContentManifestSchema,
      createCompatibilityService,
      createContentIndex,
      createNodePluginInspector,
      createPluginInspectionService,
      reconcilePluginBundle,
      DEFAULT_MATERIALIZATION_LIMITS,
      ClaimConflictError,
      ClaimedSchema,
      CompatibilityEvaluationInputSchema,
      CompatibilityPolicyRegistry,
      CompatibilityPolicyRuleRegistry,
      CompatibilityPolicyRuleSchema,
      CompatibilityPolicyRulesSchema,
      CompatibilityReportSchema,
      ComponentAssessmentSchema,
      ComponentIdSchema,
      ComponentKindRegistry,
      ComponentSchema,
      ComponentVerdictRegistry,
      ComponentVerdictSchema,
      ConfigurationOptionSchema,
      ConfigurationValueKindRegistry,
      ConfigurationValueSchema,
      DiagnosticSchema,
      DomainContractError,
      ErrorCodeRegistry,
      ErrorCodeSchema,
      FatalBoundaryCodeSchema,
      ForeignComponentDeclarationSchema,
      ForeignComponentSchema,
      GitRevisionSchema,
      HookComponentSchema,
      HookEventSchema,
      HookHandlerSchema,
      HookHandlerVariantRegistry,
      MCPFeatureSchema,
      MCPTransportSchema,
      MarketplaceAvailabilityRegistry,
      MarketplaceAvailabilitySchema,
      MarketplaceAuthoritySchema,
      MarketplaceDeclarationCategoryRegistry,
      MarketplaceEntryDeclarationSchema,
      MarketplaceInstallationPolicySchema,
      MarketplaceNameSchema,
      MarketplaceReadResultSchema,
      MarketplaceSourceSchema,
      MarketplaceSourceVariantRegistry,
      McpServerComponentSchema,
      NativeHostSchema,
      NormalizedMarketplaceEntrySchema,
      NormalizedMarketplaceSchema,
      NormalizedPluginSchema,
      NpmIntegritySchema,
      PluginComponentsSchema,
      PluginConfigurationSchema,
      PluginIdentitySchema,
      PluginKeySchema,
      PluginManifestClaimsSchema,
      PluginNameSchema,
      PluginSourceSchema,
      PluginSourceVariantRegistry,
      ProvenanceSchema,
      ReadResultSchema,
      ResolvedMarketplaceSourceSchema,
      ResolvedPluginSourceSchema,
      ResolvedPluginSourceVariantRegistry,
      RetainedMetadataSchema,
      RuntimeCapabilityAvailabilitySchema,
      RuntimeCapabilityIdSchema,
      RuntimeCapabilityRegistry,
      RuntimeCapabilityRegistrySchema,
      RuntimeCapabilitySnapshotSchema,
      RuntimeCapabilityStatusRegistry,
      RuntimeCapabilityStatusSchema,
      RuntimeRequirementAssessmentSchema,
      RuntimeRequirementIdSchema,
      RuntimeRequirementSchema,
      RuntimeRequirementStatusRegistry,
      RuntimeRequirementStatusSchema,
      SkillComponentSchema,
      SourceDocumentKindSchema,
      SourceHashSchema,
      SourceLocationSchema,
      createCompatibilityReport,
      deriveComponentId,
      createContentManifest,
      createNodeSourceMaterializers,
      createPluginIdentity,
      createSourceMaterializers,
      createResolvedMarketplaceSource,
      createResolvedPluginSource,
      deriveActivatable,
      diagnosticFromZodError,
      evaluateCompatibility,
      flattenComponents,
      verifyComponentId,
      formatPluginKey,
      hashCanonicalSource,
      hashContent,
      mergeEquivalentClaims,
      SourceMaterializationError,
      verifyContentManifest,
      verifyResolvedMarketplaceSource,
      verifyResolvedPluginSource,
      nonEmptyReadonly,
      parsePluginKey,
      schemaValues,
      serializeMarketplaceSource,
      serializePluginSource,
      claim,
      ActivationIntentSchema,
      CanonicalProjectRootSchema,
      GenerationSchema,
      HostConfigDocumentSchema,
      HostConfigDocumentSchemaV1,
      HostConfigSchemaFamily,
      ImmutableRevisionEvidenceSchema,
      InstalledPluginRecordSchema,
      InstalledRevisionRecordSchema,
      InstalledUserStateDocumentSchema,
      InstalledUserStateDocumentSchemaV1,
      InstalledUserStateSchema,
      InstalledUserStateSchemaFamily,
      MarketplaceConfigurationRecordSchema,
      MarketplaceContentRefSchema,
      MarketplaceSnapshotRecordSchema,
      PendingTransitionRefSchema,
      PluginConfigurationRefSchema,
      PluginContentRefSchema,
      PluginDataRefSchema,
      PointerDocumentKindSchema,
      PortableMarketplaceDeclarationSchema,
      PortableMarketplaceSourceSchema,
      PortablePluginConstraintSchema,
      PortablePluginDeclarationSchema,
      PortablePluginSourceSchema,
      PortableProjectDeclarationSchema,
      PortableProjectDeclarationSchemaV1,
      PortableProjectSchemaFamily,
      ProjectIdentitySchema,
      ProjectKeySchema,
      ProjectLocalStateDocumentSchema,
      ProjectLocalStateDocumentSchemaV1,
      ProjectLocalStateSchemaFamily,
      ProjectStateMutationInputSchema,
      ProjectStateMutationSchema,
      ReferenceIdentitySchema,
      ScopeContextSchema,
      ScopeReferenceSchema,
      StateBlobRefSchema,
      StateCodecError,
      StateCorruptionCodeSchema,
      StateCorruptionSchema,
      StateDocumentKindRegistry,
      StateDocumentKindSchema,
      StateDocumentPointerSchema,
      StateDocumentRegistry,
      StateLoadFailureSchema,
      StateMutationInputSchema,
      StateMutationSchema,
      StatePointersDocumentSchema,
      StatePointersDocumentSchemaV1,
      StatePointersSchemaFamily,
      StateReferenceKindRegistry,
      StateReferenceSchema,
      StateSchemaVersionSchema,
      TrustDecisionStatusSchema,
      TrustStateDocumentSchema,
      TrustStateDocumentSchemaV1,
      TrustStateRecordSchema,
      TrustStateSchemaFamily,
      TrustSubjectEvidenceSchema,
      TrustSubjectRefSchema,
      UpdateApplicationPreferenceSchema,
      UserStateMutationInputSchema,
      UserStateMutationSchema,
      assertPortableProjectDeclarationSafe,
      createInstalledPluginRecord,
      createInstalledRevisionRecord,
      createInstalledUserStateDocument,
      createMarketplaceSnapshotRecord,
      createProjectLocalStateDocument,
      createScopeContext,
      createStatePointersDocument,
      createTrustStateDocument,
      createTrustStateRecord,
      decodeInstalledPluginRecords,
      decodeInstalledUserPlugins,
      decodePortableProjectDeclaration,
      decodeProjectPlugins,
      decodeStateDocument,
      defineVersionedSchemaFamily,
      deriveMarketplaceContentRef,
      derivePendingTransitionRef,
      derivePluginConfigurationRef,
      derivePluginContentRef,
      derivePluginDataRef,
      deriveProjectKey,
      deriveStateBlobRef,
      deriveTrustSubject,
      deriveTrustSubjectRef,
      encodeStateDocument,
      getStateDocumentDefinition,
      hashStateDocument,
      isSafePortableRelativePath,
      migrateVersionedDocument,
      parsePortableProjectDeclaration,
      isVerifiedStateMutation,
      parseStateMutation,
      stateDocumentKinds,
      toScopeReference,
      validateStateMutation,
      verifyMarketplaceContentRef,
      verifyPendingTransitionRef,
      verifyPluginConfigurationRef,
      verifyPluginContentRef,
      verifyPluginDataRef,
      verifyStateBlobRef,
      verifyStatePointersScope,
      verifyTrustStateRecord,
      verifyTrustSubjectRef,
    ];

    for (const symbol of symbols) {
      expect(symbol).toBeDefined();
    }
  });

  it("keeps secret custody and policy boundaries out of the public surface", () => {
    expect(sourceApi.SensitiveValue).toBeDefined();
    expect(sourceApi.withResolvedPluginConfiguration).toBeDefined();
    expect(sourceApi.savePluginConfiguration).toBeDefined();
    expect(sourceApi.authorizeTrustCandidate).toBeDefined();
    expect(sourceApi).not.toHaveProperty("withSensitiveValue");
    expect(sourceApi).not.toHaveProperty("validateConfigurationSubmission");
    expect(sourceApi).not.toHaveProperty("createResolvedConfiguration");
  });

  it("keeps public types inferred from the exported schemas", () => {
    expectTypeOf<BundleDocumentLimitsContract>().toEqualTypeOf<z.infer<typeof BundleDocumentLimitsSchema>>();
    expectTypeOf<PluginInspectionService>().toMatchTypeOf<{ inspect: Function }>();
    expectTypeOf<PluginInspectionDependencies>().toMatchTypeOf<{ sha256: Function }>();
    expectTypeOf<BundleReconciliationInput>().toMatchTypeOf<{ manifestClaims: readonly unknown[] }>();
    expectTypeOf<BundleInspectionInput>().toEqualTypeOf<z.infer<typeof BundleInspectionInputSchema>>();
    expectTypeOf<BundleInspectionResult>().toEqualTypeOf<z.infer<typeof BundleInspectionResultSchema>>();
    expectTypeOf<ComponentLocatorClaim>().toEqualTypeOf<z.infer<typeof ComponentLocatorClaimSchema>>();
    expectTypeOf<ForeignComponentDeclaration>().toEqualTypeOf<z.infer<typeof ForeignComponentDeclarationSchema>>();
    expectTypeOf<ContentDigest>().toEqualTypeOf<z.infer<typeof ContentDigestSchema>>();
    expectTypeOf<ContentManifestEntry>().toEqualTypeOf<z.infer<typeof ContentManifestEntrySchema>>();
    expectTypeOf<ContentManifest>().toEqualTypeOf<z.infer<typeof ContentManifestSchema>>();
    expectTypeOf<SourceContext>().toMatchTypeOf<{ kind: "external" } | { kind: "marketplace" }>();
    expectTypeOf<SourceMaterializationDependencies>().toMatchTypeOf<{ sha256: Sha256 }>();
    expectTypeOf<StagingSlot>().toMatchTypeOf<{ root: string }>();
    expectTypeOf<Component>().toMatchTypeOf<z.infer<typeof ComponentSchema>>();
    expectTypeOf<ComponentAssessment>().toEqualTypeOf<z.infer<typeof ComponentAssessmentSchema>>();
    expectTypeOf<CompatibilityReport>().toEqualTypeOf<z.infer<typeof CompatibilityReportSchema>>();
    expectTypeOf<CompatibilityEvaluationInput>().toEqualTypeOf<z.infer<typeof CompatibilityEvaluationInputSchema>>();
    expectTypeOf<CompatibilityAssessmentRequest>().toMatchTypeOf<{ plugin: NormalizedPlugin }>();
    expectTypeOf<CompatibilityService>().toMatchTypeOf<{ assess: Function }>();
    expectTypeOf<RuntimeCapabilityProbe>().toMatchTypeOf<{ snapshot: Function }>();
    expectTypeOf<RuntimeCapabilityAvailability>().toEqualTypeOf<z.infer<typeof RuntimeCapabilityAvailabilitySchema>>();
    expectTypeOf<RuntimeCapabilityId>().toEqualTypeOf<z.infer<typeof RuntimeCapabilityIdSchema>>();
    expectTypeOf<RuntimeCapabilitySnapshot>().toEqualTypeOf<z.infer<typeof RuntimeCapabilitySnapshotSchema>>();
    expectTypeOf<CompatibilityPolicyRule>().toEqualTypeOf<z.infer<typeof CompatibilityPolicyRuleSchema>>();
    expectTypeOf<CompatibilityPolicyDisposition>().toEqualTypeOf<z.infer<typeof CompatibilityPolicyRuleSchema>["disposition"]>();
    expectTypeOf<CompatibilityPolicySurface>().toEqualTypeOf<z.infer<typeof CompatibilityPolicyRuleSchema>["surface"]>();
    expectTypeOf<CompatibilityPolicyRegistryType>().toEqualTypeOf<typeof import("../src/index.js").CompatibilityPolicyRegistry>();
    expectTypeOf<ConfigurationOption>().toEqualTypeOf<z.infer<typeof ConfigurationOptionSchema>>();
    expectTypeOf<ConfigurationValue>().toEqualTypeOf<z.infer<typeof ConfigurationValueSchema>>();
    expectTypeOf<Diagnostic>().toEqualTypeOf<z.infer<typeof DiagnosticSchema>>();
    expectTypeOf<DomainContractErrorType>().toMatchTypeOf<DomainContractError>();
    expectTypeOf<ErrorCode>().toEqualTypeOf<z.infer<typeof ErrorCodeSchema>>();
    expectTypeOf<FatalBoundaryCode>().toEqualTypeOf<z.infer<typeof FatalBoundaryCodeSchema>>();
    expectTypeOf<ForeignComponent>().toEqualTypeOf<z.infer<typeof ForeignComponentSchema>>();
    expectTypeOf<GitRevision>().toEqualTypeOf<z.infer<typeof GitRevisionSchema>>();
    expectTypeOf<HookComponent>().toEqualTypeOf<z.infer<typeof HookComponentSchema>>();
    expectTypeOf<HookHandler>().toEqualTypeOf<z.infer<typeof HookHandlerSchema>>();
    expectTypeOf<JsonValue>().toEqualTypeOf<z.infer<typeof JsonValueSchema>>();
    expectTypeOf<MarketplaceAuthority>().toEqualTypeOf<z.infer<typeof MarketplaceAuthoritySchema>>();
    expectTypeOf<MarketplaceAvailability>().toEqualTypeOf<z.infer<typeof MarketplaceAvailabilitySchema>>();
    expectTypeOf<MarketplaceEntryDeclaration>().toEqualTypeOf<z.infer<typeof MarketplaceEntryDeclarationSchema>>();
    expectTypeOf<MarketplaceInstallationPolicy>().toEqualTypeOf<z.infer<typeof MarketplaceInstallationPolicySchema>>();
    expectTypeOf<MarketplaceName>().toEqualTypeOf<z.infer<typeof MarketplaceNameSchema>>();
    expectTypeOf<MarketplaceReadResult>().toEqualTypeOf<z.infer<typeof MarketplaceReadResultSchema>>();
    expectTypeOf<MarketplaceSource>().toEqualTypeOf<z.infer<typeof MarketplaceSourceSchema>>();
    expectTypeOf<McpServerComponent>().toEqualTypeOf<z.infer<typeof McpServerComponentSchema>>();
    expectTypeOf<NativeHost>().toEqualTypeOf<z.infer<typeof NativeHostSchema>>();
    expectTypeOf<NormalizedMarketplace>().toEqualTypeOf<z.infer<typeof NormalizedMarketplaceSchema>>();
    expectTypeOf<NormalizedMarketplaceEntry>().toEqualTypeOf<z.infer<typeof NormalizedMarketplaceEntrySchema>>();
    expectTypeOf<NormalizedPlugin>().toEqualTypeOf<z.infer<typeof NormalizedPluginSchema>>();
    expectTypeOf<NpmIntegrity>().toEqualTypeOf<z.infer<typeof NpmIntegritySchema>>();
    expectTypeOf<PluginComponents>().toEqualTypeOf<z.infer<typeof PluginComponentsSchema>>();
    expectTypeOf<PluginConfiguration>().toEqualTypeOf<z.infer<typeof PluginConfigurationSchema>>();
    expectTypeOf<PluginIdentity>().toEqualTypeOf<z.infer<typeof PluginIdentitySchema>>();
    expectTypeOf<PluginKey>().toEqualTypeOf<z.infer<typeof PluginKeySchema>>();
    expectTypeOf<PluginName>().toEqualTypeOf<z.infer<typeof PluginNameSchema>>();
    expectTypeOf<PluginSource>().toEqualTypeOf<z.infer<typeof PluginSourceSchema>>();
    expectTypeOf<Provenance>().toEqualTypeOf<z.infer<typeof ProvenanceSchema>>();
    expectTypeOf<ReadResult<unknown>>().toMatchTypeOf<ReadResult<unknown>>();
    expectTypeOf<ResolvedMarketplaceSource>().toEqualTypeOf<z.infer<typeof ResolvedMarketplaceSourceSchema>>();
    expectTypeOf<ResolvedPluginSource>().toEqualTypeOf<z.infer<typeof ResolvedPluginSourceSchema>>();
    expectTypeOf<RetainedMetadata>().toEqualTypeOf<z.infer<typeof RetainedMetadataSchema>>();
    expectTypeOf<RuntimeRequirement>().toEqualTypeOf<z.infer<typeof RuntimeRequirementSchema>>();
    expectTypeOf<RuntimeRequirementAssessment>().toEqualTypeOf<z.infer<typeof RuntimeRequirementAssessmentSchema>>();
    expectTypeOf<RuntimeRequirementId>().toEqualTypeOf<z.infer<typeof RuntimeRequirementIdSchema>>();
    expectTypeOf<RuntimeRequirementStatus>().toEqualTypeOf<z.infer<typeof RuntimeRequirementStatusSchema>>();
    expectTypeOf<SkillComponent>().toEqualTypeOf<z.infer<typeof SkillComponentSchema>>();
    expectTypeOf<SourceDocumentKind>().toEqualTypeOf<z.infer<typeof SourceDocumentKindSchema>>();
    expectTypeOf<SourceHash>().toEqualTypeOf<z.infer<typeof SourceHashSchema>>();
    expectTypeOf<SourceLocation>().toEqualTypeOf<z.infer<typeof SourceLocationSchema>>();
    expectTypeOf<ComponentId>().toEqualTypeOf<z.infer<typeof ComponentIdSchema>>();
    expectTypeOf<Claimed<string>>().toMatchTypeOf<{ value: string }>();
    expectTypeOf<CollectionReadResult<unknown>>().toMatchTypeOf<{ items: readonly unknown[] }>();
    expectTypeOf<Sha256>().toBeFunction();
    expectTypeOf<HostConfigDocumentV1>().toEqualTypeOf<z.infer<typeof HostConfigDocumentSchemaV1>>();
    expectTypeOf<InstalledUserStateDocumentV1>().toEqualTypeOf<z.infer<typeof InstalledUserStateDocumentSchemaV1>>();
    expectTypeOf<ProjectLocalStateDocumentV1>().toEqualTypeOf<z.infer<typeof ProjectLocalStateDocumentSchemaV1>>();
    expectTypeOf<PortableProjectDeclarationV1>().toEqualTypeOf<z.infer<typeof PortableProjectDeclarationSchemaV1>>();
    expectTypeOf<StatePointersDocumentV1>().toEqualTypeOf<z.infer<typeof StatePointersDocumentSchemaV1>>();
    expectTypeOf<TrustStateDocumentV1>().toEqualTypeOf<z.infer<typeof TrustStateDocumentSchemaV1>>();
    expectTypeOf<StateDocumentByKind<"hostConfig">>().toEqualTypeOf<HostConfigDocumentV1>();
    expectTypeOf<UnverifiedStateMutation>().toEqualTypeOf<z.infer<typeof StateMutationInputSchema>>();
    expectTypeOf<StateMutationInput>().toEqualTypeOf<UnverifiedStateMutation>();
    expectTypeOf<StateMutation>().toEqualTypeOf<VerifiedStateMutation>();
    expectTypeOf<UnverifiedStateMutation>().not.toMatchTypeOf<StateMutation>();
    expectTypeOf<StateCommitResult>().toMatchTypeOf<{ kind: "committed" | "stale-generation" }>();
    expectTypeOf<StateLoadResult>().toMatchTypeOf<{ ok: boolean }>();
    expectTypeOf<UserGenerationSnapshot>().toMatchTypeOf<{ generation: Generation }>();
    expectTypeOf<ProjectGenerationSnapshot>().toMatchTypeOf<{ generation: Generation }>();
    expectTypeOf<LifecycleStateStore>().toMatchTypeOf<{ read: Function; commit: Function }>();
  });
});
